// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qiTbzYo_w3nkFandoneVJfnzVjKlPcg',
    appId: '1:336729405422:web:6a45be285bcecefa97c0ff',
    messagingSenderId: '336729405422',
    projectId: 'skillsell',
    authDomain: 'skillsell.firebaseapp.com',
    storageBucket: 'skillsell.appspot.com',
    measurementId: 'G-KPJ3VVYDV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeM1RHKkOk4qsrwenAX3i-uqALj-l969c',
    appId: '1:336729405422:android:69298dfed70b8cf797c0ff',
    messagingSenderId: '336729405422',
    projectId: 'skillsell',
    storageBucket: 'skillsell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fSbuoTA5m-Ci25V3hNaZvau2ZB9wwqY',
    appId: '1:336729405422:ios:170e752973be145b97c0ff',
    messagingSenderId: '336729405422',
    projectId: 'skillsell',
    storageBucket: 'skillsell.appspot.com',
    iosClientId: '336729405422-vr7ob3emecbrak94hi7787pna8p4mlb2.apps.googleusercontent.com',
    iosBundleId: 'com.swirx.skillsell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6fSbuoTA5m-Ci25V3hNaZvau2ZB9wwqY',
    appId: '1:336729405422:ios:42424eb16a08c5fe97c0ff',
    messagingSenderId: '336729405422',
    projectId: 'skillsell',
    storageBucket: 'skillsell.appspot.com',
    iosClientId: '336729405422-fiba48o6u4af7dbckfliu9fu5ehm31ie.apps.googleusercontent.com',
    iosBundleId: 'com.swirx.skillsell.RunnerTests',
  );
}
